### ISSUE TITLE
Parameter videoAllowed isn't used

### ISSUE THREAD

**Issue by haydgately** [karenxpn/CameraXPN#1]
Hi, I am trying to implement an app where you can record video.

Unfortunately, your library only records video when you long press instead of pressing record. I was wondering if the parameter in the documentation of "videoAllowed" would do this? This parameter is not used however. 

Any help is much appreciated

**Comment by karenxpn** [comment]
Hi, thanks for your note. The click gesture is only for taking pictures while the long press is for taking video recordings.

**Comment by karenxpn** [comment]
Thanks for your interest, I appreciate any kind of contribution.
